name: Publish Addon to Wago

on:
  push:
    branches:
      - main  # your default branch

jobs:
  wago:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Publish addon to Wago
      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
